# Generated by Django 3.2.7 on 2021-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('s', 'оплачено'), ('w', 'ожидает оплаты'), ('r', 'отклонено')], default='w', max_length=30, verbose_name='статус'),
        ),
    ]
