# Generated by Django 3.2.7 on 2021-09-03 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210903_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='баланс'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо вводить в формате: '+799999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{7,15}$')], verbose_name='номер телефона'),
        ),
    ]
