version: '3.2'

services:
  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
    python manage.py makemigrations &&
    python manage.py migrate &&
    gunicorn scriptshop.wsgi -b 0.0.0.0:8080
    "


  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 85:80
    depends_on:
      - nginx
