# Generated by Django 3.2.7 on 2021-09-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210903_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='userprofile_avatars', verbose_name='аватарка'),
        ),
    ]
